<?php

namespace ContainerQP02qKY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ImportCommand' shared autowired service.
     *
     * @return \App\Command\ImportCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\ImportCommand'] = $instance = new \App\Command\ImportCommand(new \App\Service\XmlImportService(), new \App\Service\SqliteImportService(($container->privates['App\\Repository\\ArticleRepository'] ?? $container->load('getArticleRepositoryService'))));

        $instance->setName('app:import');

        return $instance;
    }
}
