<?php

namespace Container6lQThFq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsoleErrorListenerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\EventListener\ConsoleErrorListener' shared autowired service.
     *
     * @return \App\EventListener\ConsoleErrorListener
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\EventListener\\ConsoleErrorListener'] = new \App\EventListener\ConsoleErrorListener();
    }
}
