<?php

namespace Container6lQThFq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportCommandService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Command\ImportCommand' shared autowired service.
     *
     * @return \App\Command\ImportCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\ImportCommand'] = $instance = new \App\Command\ImportCommand(($container->privates['App\\Service\\XmlImportService'] ??= new \App\Service\XmlImportService()), ($container->privates['App\\Service\\SqliteImportService'] ?? $container->load('getSqliteImportServiceService')));

        $instance->setName('app:import');

        return $instance;
    }
}
