<?php

namespace Container6lQThFq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSqliteImportServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\SqliteImportService' shared autowired service.
     *
     * @return \App\Service\SqliteImportService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\SqliteImportService'] = new \App\Service\SqliteImportService(($container->privates['App\\Repository\\ArticleRepository'] ?? $container->load('getArticleRepositoryService')));
    }
}
