<?php

namespace Container6lQThFq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getXmlImportServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\XmlImportService' shared autowired service.
     *
     * @return \App\Service\XmlImportService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\XmlImportService'] = new \App\Service\XmlImportService();
    }
}
