<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQP02qKY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQP02qKY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQP02qKY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQP02qKY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQP02qKY\App_KernelDevDebugContainer([
    'container.build_hash' => 'QP02qKY',
    'container.build_id' => '24551d81',
    'container.build_time' => 1718013860,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQP02qKY');
